[window]
decorations = "none"  # Hide the title bar
opacity = 0.9         # Use window.opacity instead of background_opacity
dynamic_title = false # Use window.dynamic_title instead of dynamic_title

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 10

[colors]
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black = '#1e2127'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#abb2bf'

# Bright colors
[colors.bright]
black = '#5c6370'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#e4e4e4'

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/fish"

[keyboard]
bindings = [{ key = "Q", mods = "Command", action = "Quit" }]
