format = """$directory\
$git_branch\
$git_metrics\
$cmd_duration\
$line_break\
$character"""

command_timeout = 200
add_newline = false

[directory]
style = "%COLORCODE"
read_only = " 𝑟𝑒𝑎𝑑 𝑜𝑛𝑙𝑦"
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = "⎇  "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
min_time = 2000
format = "[•](bold green) took [$duration]($style)"

[character]
success_symbol = "[❯](#3684DD)"
error_symbol = "[✗](#E53935)"
vicmd_symbol = "[❮](#4CAF50)"
